name: Claude Code Integration
on:
  workflow_dispatch:
    inputs:
      analysis_type:
        description: 'Type of analysis to run'
        required: false
        default: 'complete'
        type: choice
        options:
        - complete
        - gmail
        - narrative
        - monitoring
  push:
    branches: [ main, master ]
  pull_request:
    branches: [ main, master ]

jobs:
  claude-integration:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install pandas numpy networkx textblob requests schedule

      - name: Verify legal study tools
        run: |
          chmod +x ./legal_study
          ./legal_study --help || echo "Legal study system ready"

      - name: Run system verification
        run: |
          python3 -c "
          import sys
          sys.path.append('./backend')
          try:
              from MASTER_INTELLIGENCE_SYSTEM import MasterIntelligenceSystem
              from GMAIL_COMPLETE_EXTRACTION_SYSTEM import CompleteGmailAnalysisSystem
              from NARRATIVE_INTELLIGENCE_SYSTEM import ComprehensiveIntelligenceSystem
              print('✅ All legal intelligence systems imported successfully')
          except ImportError as e:
              print(f'❌ Import error: {e}')
              sys.exit(1)
          "

      - name: Claude Code Integration
        uses: anthropics/claude-code-action@v1
        with:
          api-key: ${{ secrets.ANTHROPIC_API_KEY }}
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}